version: '3'
services:
  # vlc:
  #   build: ./docker/vlc/
  #   volumes:
  #     - ./audio:/audio

  stream_recorder:
    build: ./docker/stream-recorder/
    volumes:
      - ./audio:/audio

  webserver:
    image: nginx:1.12-alpine
    depends_on:
      - php
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/var/www/app
      - ./audio:/var/www/app/public/audio:ro
    ports:
      - 80:80

  php:
    build: ./docker/php
    volumes:
      - ./app:/var/www/app
      - ./audio:/audio:ro
    working_dir: /var/www/app
    environment:
      AUDIO_BASE_URI: http://localhost/audio
      PODCASTS_FILE: /etc/stream-recorder/podcasts.json
