version: '3'
services:
  # vlc:
  #   build: ./docker/vlc/
  #   volumes:
  #     - ./audio:/audio

  stream-saver:
    build: ./docker/stream-saver/
    volumes:
      - ./audio:/audio

  webserver:
    image: nginx:1.12-alpine
    depends_on:
      - php
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/var/www/app
      - ./audio:/var/www/app/public/audio:ro
    ports:
      - 8083:80

  php:
    image: php:7.2-fpm-alpine
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./app:/var/www/app
      - ./audio:/audio:ro
    working_dir: /var/www/app

  composer:
    image: composer:1.6
    volumes:
      - ./app:/var/www/app
    working_dir: /var/www/app
